modLoader="javafml"
loaderVersion="[40,)"
license="CC BY-NC-SA 4.0"
logoFile="logo.png"
[[mods]]
modId="sculkmic"
version="${file.jarVersion}"
displayName="ยง3Sculk ยง7Microphone"
displayURL="https://www.curseforge.com/minecraft/mc-mods/sculk-microphone"
#credits="Towo"
authors="Towo"
description='''
This mod adds:
- Vibration listener activation (Sensor, Warden) when talking into your microphone.
    - A comparator's output will be determined by the volume of your voice.
- Configurable settings (client-side and server-side)
'''

[[dependencies.sculkmic]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sculkmic]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
