modLoader="javafml"
loaderVersion="[40,)"
license="CC BY-NC-SA 4.0"
[[mods]]
modId="sculkmic"
version="${file.jarVersion}"
displayName="Sculk Microphone Detection"
logoFile="examplemod.png"
credits="Towo"
authors="Towo"
description='''
Adds microphone support for activating sculk sensors! Just talk loud enough and a nearby sculk sensor should activate!
A sculk sensor's comparator output is also affected by the volume of your input.
'''

[[dependencies.sculkmic]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sculkmic]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sculkmic]]
modId="voicechat"
mandatory=true
versionRange="[${voicechat_dependency},)"
ordering="AFTER"
side="BOTH"
